
#
/system/framework/framework.jar
#
/system/framework/framework.jar
0
(/system/framework/framework-graphics.jar36
0
(/system/framework/framework-graphics.jar36
0
(/system/framework/framework-location.jar36
0
(/system/framework/framework-location.jar36

/system/framework/ext.jar

/system/framework/ext.jar
*
&/system/framework/telephony-common.jar
*
&/system/framework/telephony-common.jar
%
!/system/framework/voip-common.jar
%
!/system/framework/voip-common.jar
$
 /system/framework/ims-common.jar
$
 /system/framework/ims-common.jar
E
=/system/framework/framework-ondeviceintelligence-platform.jar36
E
=/system/framework/framework-ondeviceintelligence-platform.jar36
=
9/system_ext/framework/mediatek-carrier-config-manager.jar
=
9/system_ext/framework/mediatek-carrier-config-manager.jar
-
)/system_ext/framework/mediatek-common.jar
-
)/system_ext/framework/mediatek-common.jar
0
,/system_ext/framework/mediatek-framework.jar
0
,/system_ext/framework/mediatek-framework.jar
/
+/system_ext/framework/mediatek-ims-base.jar
/
+/system_ext/framework/mediatek-ims-base.jar
0
,/system_ext/framework/moto-echolocateapi.jar
0
,/system_ext/framework/moto-echolocateapi.jar
(
$/system_ext/framework/payjoy-api.jar
(
$/system_ext/framework/payjoy-api.jar
1
-/apex/com.android.i18n/javalib/core-icu4j.jar
1
-/apex/com.android.i18n/javalib/core-icu4j.jar